global:
  evaluation_interval: 10s
  scrape_interval: 15s

rule_files:
  - "/etc/prometheus/prometheus.rules"

scrape_configs:
- job_name: node
  static_configs:
  - targets: ['node-exporter:9100']

- job_name: 'blackbox'
  metrics_path: /probe
  params:
    module: [http_2xx]
  file_sd_configs:
    - files: ['/etc/blackbox/blackbox_targets.yml']
  relabel_configs:
    - source_labels: [__address__]
      regex: (.*)(:80)?
      target_label: __param_target
    - source_labels: [__param_target]
      regex: (.*)
      target_label: instance
      replacement: ${1}
    - source_labels: []
      regex: .*
      target_label: __address__
      replacement: blackbox:9115