---
- hosts: test
  become: true
  vars_files:
    - vars/default.yml

  tasks:
    - name: Pull default Docker image
      docker_image:
        name: "{{ container_image }}"
        source: pull

    - name: Create default containers
      docker_container:
        name: "{{ container_name }}"
        image: "{{ container_image }}"
        state: started
        restart: yes
        ports:
          - "80:80"

    - name: Create index.html
      template:
        src: templates/index.j2
        dest: /tmp/index.html

    - name: Copy index.html into container
      shell: docker cp /tmp/index.html nginx:/usr/share/nginx/html/index.html

