---
# tasks file for mysql
- name: install package
  apt:
    name: vsftpd
    update_cache: yes
 
- name: copy config
  copy:
    src: files/vsftpd.conf
    dest: /etc/vsftpd.conf

- name: start service
  service:
    name: vsftpd
    state: started
    enabled: yes