- hosts: remote
  gather_facts: no
  become: yes
  vars_files:
    - vars/default.yml

  tasks:
    - name: Create new user
      ansible.builtin.user:
        name: "{{ user_name }}"
        comment: Test user

    - name: make .ssh direcotry
      file:
        path: "/home/{{ user_name }}/.ssh"
        state: directory

    - name: copy id_rsa
      copy:
        src: "{{ id_rsa }}"
        dest: /home/user1/.ssh/id_rsa.pub